[build]
command = "pnpm install && pnpm run build"
publish = ".next"

[functions.environment]
CONTENTFUL_ACCESS_TOKEN = ""
CONTENTFUL_SPACE_ID = ""

[[plugins]]
package = "@netlify/plugin-nextjs"

[build.environment]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/google-chrome-stable"
